name: CI/CD EAS

on:
  workflow_dispatch:

jobs:
  CI:
    name: CI
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        run: yarn

      - name: Setup EAS
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          packager: yarn
          token: ${{ secrets.EAS_EXPO_TOKEN }}

      - name: Build Android
        run: eas build --platform android --profile preview --non-interactive --no-wait
